apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: loan-project

configMapGenerator:
- name: loan-rules-app-properties
  files:
  - loan-rules-application.properties
  options:
    disableNameSuffixHash: true
- name: loan-process-app-properties
  files:
  - loan-process-application.properties
  options:
    disableNameSuffixHash: true
- name: data-index-properties
  files:
  - data-index.properties
  options:
    disableNameSuffixHash: true

resources:
- ../../base


