apiVersion: v1
data:
  application.properties: |-
    quarkus.swagger-ui.always-include=true
    quarkus.http.cors.origins="/.*/"

    quarkus.rest-client.loan-rules-app.url=http://loan-rules-app:80
    quarkus.rest-client.loan-rules-app.scope=javax.inject.Singleton

    # kogito.data-index.url=localhost:data-index-infinispan:80

    quarkus.infinispan-client.use-auth=true
    quarkus.infinispan-client.hosts=kogito-infinispan:11222
    quarkus.infinispan-client.username=developer
    quarkus.infinispan-client.password=HxXLVUTxFhXiutPA
    
    kafka.bootstrap.servers=kogito-kafka-kafka-bootstrap:9092

    mp.messaging.outgoing.kogito-processinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-processinstances-events.topic=kogito-processinstances-events
    mp.messaging.outgoing.kogito-processinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-usertaskinstances-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-usertaskinstances-events.topic=kogito-usertaskinstances-events
    mp.messaging.outgoing.kogito-usertaskinstances-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

    mp.messaging.outgoing.kogito-variables-events.connector=smallrye-kafka
    mp.messaging.outgoing.kogito-variables-events.topic=kogito-variables-events
    mp.messaging.outgoing.kogito-variables-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

kind: ConfigMap
metadata:
  name: loan-process-app-properties
