apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: protpbuf-config
  files:
  - LoanApplicationProcess.proto
  - list.json
  options:
    disableNameSuffixHash: true
