apiVersion: rhpam.kiegroup.org/v1
kind: KogitoRuntime
metadata:
  name: loan-rules-app
  namespace: loan-project
spec:
  replicas: 3
  image: 'image-registry.openshift-image-registry.svc:5000/openshift/loan-rules-app:v1'
  # env:
  #   - name: KOGITO_DATAINDEX_HTTP_URL
  #     value: http://data-index.kogito
  #   - name: KOGITO_DATAINDEX_WS_URL
  #     value: ws://data-index.kogito