---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loan-app-dev-ingress
  namespace: loan-app-dev
spec:
  rules:
  - host: loan-app-dev.65e5dba7a7df0d0011fcf595.cloud.techzone.ibm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: loan-process-app
            port:
              number: 80
  ingressClassName: nginx